### ISSUE TITLE
MSIgDB gene sets origin

### ISSUE THREAD

**Issue by pikapika505** [wallet-maker/cytopus#16]
Thank you for creating such a convenient knowledge base. I have a question about its curation. Are the pathways added by the MSigDB team similar to those in MSigDB? For instance, in Cytopus, the pathway "all_p53-signaling" includes 210 genes. However, in MSigDB, there are numerous p53-related pathways with varying numbers of up- or downregulated genes. How were these pathways curated?

Additionally, are all the genes in a single cell type or process upregulated? If so, does this imply that Spectra identifies latent factors where all genes are upregulated?

**Comment by wallet-maker** [comment]
Hi, 

thanks for using Cytopus. This is an excellent question. 

We are aiming to improve documentation and transparency on how gene sets were generated in future releases. Right now Cytopus includes little but helpful information about this which may give you some indication on this.


```
#import packages
import cytopus as cp
import pandas as pd
import scanpy as sc

#load Knowledge Base
G = cp.KnowledgeBase()

#access metadata for a specific gene set
G.graph.nodes['all_p53-signaling']
```

Out:
```
{'version_id': 'v_hs99',
 'author': 'Arthur_Liberzon_(MSigDB Team), wallet',
 'license': 'Creative Commons Attribution 4.0 International License',
 'license_link': 'https://www.gsea-msigdb.org/gsea/msigdb_license_terms.jsp',
 'license_type': 'c',
 'gene_set_type': 'manual_external',
 'gene_set_topic': 'signaling'}
```

As you can see here the gene set you were asking about includes both the MsigDB Team authors as well as my alias "wallet". So to answer your first question: **Yes, this is similar to the MSigDB geneset specifically the [HALLMARK_P53_PATHWAY](https://www.gsea-msigdb.org/gsea/msigdb/human/geneset/HALLMARK_P53_PATHWAY.html).** The gene set type is of 'gene_set_type' 'manual external' which means that it includes external gene sets which were manually modified . More details about this nomenclature can be found in the Methods section of the [manuscript](https://doi.org/10.1038/s41587-023-01940-3). I believe on MSigDB there is also some information how the Hallmark gene sets were created.

This specific gene set contains additional genes which are upregulated upon p53 induction in experimental systems (e.g. see this [paper](https://doi.org/10.1084/jem.20130783). **In general we only try to include genes which are upregulated or must be expressed for the related cellular process to be executed**. Of course this may not be true in all contexts and some of the data we are basing these curations on may include noise. **However, the gene sets do not have to be perfect for Spectra because it will find latent factors which include co-expressed genes and remove genes which are not in the context under investigation**. 

Let me know if this helps .

**Comment by pikapika505** [comment]
thank you for the explanation!
